name: cd

on:
  push:
    branches:
      - main
    paths:
      - 'src/terraform/**'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  working_directory: "src/terraform"
  application: "application-name"
  environment: "dev"

jobs:
  terraform:
    name: 'Terraform Apply'
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5
          terraform_wrapper: false

      - name: Terraform Init (with backend config)
        working-directory: ${{ env.working_directory }}
        env:
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        run: |
          terraform init \
            -backend-config="storage_account_name=${{ secrets.TF_BACKEND_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.TF_BACKEND_CONTAINER_NAME }}" \
            -backend-config="access_key=${{ secrets.TF_BACKEND_ACCESS_KEY }}" \
            -backend-config="key=${{ env.application }}-${{ env.environment }}.tfstate"

      - name: Terraform Apply
        working-directory: ${{ env.working_directory }}
        env:
          TF_VAR_application: ${{ env.application }}
          TF_VAR_environment: ${{ env.environment }}
          azure_client_id: ${{ secrets.AZURE_CLIENT_ID }}
          azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        run: terraform apply -auto-approve
