
name : "install snowflake CLI"
on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/run_snowflake_scripts.yaml'
      - 'src/snowflake/**'
  pull_request:
    branches:
      - main
jobs:
  install_snowflake_cli:
    runs-on: ubuntu-latest
    steps:
      - name: Install Snowflake CLI
        run: |
          curl -o- https://raw.githubusercontent.com/snowflakedb/snowflake-cli/main/install.sh | bash
      - name: Verify Installation
        run: |
          snowsql --version
      - name: Add Snowflake CLI to PATH
        run: |
          echo "$HOME/.snowflake/bin" >> $GITHUB_PATH
      - name: Confirm Snowflake CLI in PATH
        run: |
          which snowsql
      - name: Run a sample Snowflake command
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWSQL_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: |
          snowsql -a $SNOWSQL_ACCOUNT -u $SNOWSQL_USER -p $SNOWSQL_PASSWORD -q "SELECT CURRENT_VERSION();"  
