name: "Install Snowflake CLI"

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/run_snowflake_scripts.yaml'
      - 'src/snowflake/**'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  working_directory: "src/snowflake"
  application: "azure_config"
  environment: "dev"

jobs:
  install_snowflake_cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v4

      - name: Install Snowflake CLI (3.14.0)
        run: |
          wget https://sfc-repo.snowflakecomputing.com/snowflake-cli/linux_x86_64/3.14.0/snowflake-cli-3.14.0.x86_64.deb
          sudo apt-get update
          sudo apt-get install -y ./snowflake-cli-3.14.0.x86_64.deb
          echo "/usr/bin" >> $GITHUB_PATH
          echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Verify Snowflake CLI Installation
        run: |
          which snowflake
          snowflake --version
      - name: List Snowflake CLI Commands 
        run: snowflake --help 
          
