name: Run Snowflake Script (SnowSQL CLI)

on:
  workflow_dispatch:    # Manual trigger
  push:
    branches:
      - main
    paths:
      - 'src/snowflake/**'
      - '.github/workflows/run_snowflake_scripts.yaml'

jobs:
  run-snowflake-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install SnowSQL CLI (latest)
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/snowsql-install.sh
          bash snowsql-install.sh
          export PATH=$PATH:$HOME/bin

      - name: Run SQL script in Snowflake
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}
          SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
          SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          snowsql \
            -a $SNOWFLAKE_ACCOUNT \
            -u $SNOWFLAKE_USER \
            -p $SNOWFLAKE_PASSWORD \
            -r $SNOWFLAKE_ROLE \
            -d $SNOWFLAKE_DATABASE \
            -s $SNOWFLAKE_SCHEMA \
            -w $SNOWFLAKE_WAREHOUSE \
            -f src/snowflake/retail_copy.sql
